// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXhUuOQc9QjPcUC5AVLu9keT6K3CLjv8',
    appId: '1:879649884314:web:bc47ba65da4f78e980b723',
    messagingSenderId: '879649884314',
    projectId: 'project-36e2b',
    authDomain: 'project-36e2b.firebaseapp.com',
    storageBucket: 'project-36e2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCKgnmiHm1xXHxcap6t2c-yea-C7eaKY',
    appId: '1:879649884314:android:265a53d7a32ee25c80b723',
    messagingSenderId: '879649884314',
    projectId: 'project-36e2b',
    storageBucket: 'project-36e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0HM7MTi8tJgvoJBzMgAJnEZy45eprQSY',
    appId: '1:879649884314:ios:b23baa72da4909fe80b723',
    messagingSenderId: '879649884314',
    projectId: 'project-36e2b',
    storageBucket: 'project-36e2b.firebasestorage.app',
    iosBundleId: 'com.example.appfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0HM7MTi8tJgvoJBzMgAJnEZy45eprQSY',
    appId: '1:879649884314:ios:b23baa72da4909fe80b723',
    messagingSenderId: '879649884314',
    projectId: 'project-36e2b',
    storageBucket: 'project-36e2b.firebasestorage.app',
    iosBundleId: 'com.example.appfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrXhUuOQc9QjPcUC5AVLu9keT6K3CLjv8',
    appId: '1:879649884314:web:56e521207e9636e080b723',
    messagingSenderId: '879649884314',
    projectId: 'project-36e2b',
    authDomain: 'project-36e2b.firebaseapp.com',
    storageBucket: 'project-36e2b.firebasestorage.app',
  );
}
